<?xml version="1.0"?>
<package format="3">
  <name>move_to_path_idx</name>
  <version>0.0.0</version>
  <description>Move a mobile base or UR TCP to a selected path index using an external robot pose.</description>
  <maintainer email="rosmatch@todo.todo">rosmatch</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>builtin_interfaces</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
