<?xml version="1.0"?>
<package format="3">
  <name>am_bringup</name>
  <version>0.0.0</version>
  <description>Demo launch/config glue for additive-manufacturing simulation path-following experiments.</description>
  <maintainer email="rosmatch@todo.todo">rosmatch</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>base_trajectory_follower</exec_depend>
  <exec_depend>am_operator_gui</exec_depend>
  <exec_depend>am_jparse_controller</exec_depend>
  <exec_depend>move_to_path_idx</exec_depend>
  <exec_depend>parse_paths</exec_depend>
  <exec_depend>print_path_monitoring</exec_depend>
  <exec_depend>robotnik_rbvogui_tum</exec_depend>
  <exec_depend>ur_trajectory_follower</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
